# Generated by Django 2.2.12 on 2020-05-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='target_story_id',
            new_name='story_id',
        ),
    ]
