# Generated by Django 2.2.12 on 2020-05-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200513_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='next_story', to='book.Story'),
        ),
    ]
