# Generated by Django 2.2.12 on 2020-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_choice_next_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
