# Generated by Django 2.2.12 on 2020-05-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200513_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='body',
        ),
    ]
