# Generated by Django 2.2.12 on 2020-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200513_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateField(editable=False, verbose_name='publish date'),
        ),
    ]
