# Generated by Django 2.2.12 on 2020-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200515_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateField(verbose_name='publish date'),
        ),
    ]
