# Generated by Django 2.2.12 on 2020-05-16 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_auto_20200516_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.CreateModel(
            name='ChoiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Choice Datetime')),
                ('host_story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_story_id', to='book.Story')),
                ('next_story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_story_id', to='book.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
